version: "3.0"
services:
  frontend:
    image: gudururamprasad/employee-board:latest
    container_name: react
    stdin_open: true
    ports:
      - "3001:3000"

  nodejs:
    image: gudururamprasad/employee:latest
    container_name: nodejs
    depends_on:
      - postgres
    ports:
      - "5001:5000"

  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      DB_SCHEMA: testdb
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_HOST: localhost
    ports:
      - "5433:5432"

