version: "3.0"
services:
  client:
    image: gudururamprasad/employee-board:latest
    container_name: react
    stdin_open: true
    ports:
      - "3000:3000"

  server:
    image: gudururamaprasad/employee:latest
    container_name: nodejs
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  postgres:
    image: postgres
    container_name: postgresdb
    ports:
      - "5432:5432"
